---
title: "Codebook for Getting and Cleaning Data Project"
author: "Tiby Kantrowitz"
date: "27 December, 2015"
output:
  text_file: happydata.txt
    keep_md: yes
---

## Project Description
This collection represents data collected from the output of the accelerometer and gyroscope contained within a Samsung Galaxy S smartphone. 

Overall, the data describes a broad collection of measurements. However, the script in this repository summarizes only a subset of that collection and presents it in tidy data fashion. The script makes the rest of the data available within the directory structure, in case it is needed for further summary, but does no further processing on it nor is that data included in this repository.

##Study design and data processing
Thirty (30) volunteers aged between 19-48 were individually asked to wear the phone while performing the following activities:
  * a) Walking
  * b) Walking_Upstairs
  * c) Walking_Downstairs
  * d) Sitting
  * e) Standing
  * f) Laying
Measurements were obtained via the phone's accelerometer and gyroscope for 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz, and were labeled manually using the video recorded of the subjects' performance of the activities to verify the actions.

Of the set obtained, seventy percent (70%) was randomly separated into the training data, and thirty percent (30%) were separated into the test data.

###Collection of the raw data
From the study notes: 
>"The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding>windows of 2.56 sec and 50% overlap (128 readings/window). The sensor >acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain."

_http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones_

##Creating the tidy datafile

The script checks to see if the zip file has been downloaded and if it has been unzipped. As necessary, it unzips the zip file, or downloads and unzips it, then moving into UCI HAR Dataset as the working directory.

Next, it loads and merges the training and testing data, omitting the measurements for inertial signals as specified by the assignment. It adjusts the names of the variables for ease of reading, loads the subjects (integers), swaps the Activity numbers for the names of the Activities the subjects performed, combines everything, summarizes the means of the standard deviation and the means of the measurements, and outputs the tidy set to a file called "happydata.txt."

###Guide to create the tidy data file
The following activities were performed on the downloaded data files.
  1. The inertial signal files were ignored, as requested.
  2. The training and test data sets were merged.
  3. The Activity numbers were converted to meaningful names.
  4. The Subjects were loaded.
  5. Of the total data loaded, only that pertaining to means (on all axes) and standard deviations was kept.
  6. The variables for the measurements in the step above were corrected accordinging to tidy data principles as per the Google stylebook, available here: _Here: https://google.github.io/styleguide/Rguide.xml_
  7. The data for each Subject, each Activity and each of the measurements kept was summarized by taking the mean for each relevant grouping.
  8. The final table presents the data according to the principles of tidiness.

###Cleaning of the data
The cleaning portion of this script includes the following activities, after the relevant sector of the data was retained as described above.
  
  1. "t" was changed to "Time"
  2. "f" was changed to "frequency"
  3. The misprint of "BodyBody" was changed to "Body"
  4. "std()" was written out to "StandardDev" and "mean()" to "Mean"
  5. Dashes and parentheses were removed.
  6. The factor levels of the Activities were written out as follows:
    * 1 = WALKING
    * 2 = WALKING_UPSTAIRS
    * 3 = WALKING_DOWNSTAIRS
    * 4 = SITTING
    * 5 = STANDING
    * 6 = LAYING

##Description of the variables in the happydata.txt file
General description of the file including:
 - Dimensions of the dataset : A data.frame of 180 obs. of 68 variables.
 - Summary of the data: 30 subjects, 6 Activities, and 66 measurements. The data presents the mean of the raw measurements taken for each measurement type, for each activity as performed by each subject.
 - The total variables included are the following:

> [1] "Subject"                        "Activity"                       "timeBodyAccMeanX"           
 [4] "timeBodyAccMeanY"               "timeBodyAccMeanZ"               "timeGravityAccMeanX"           
 [7] "timeGravityAccMeanY"            "timeGravityAccMeanZ"            "timeBodyAccJerkMeanX"          
[10] "timeBodyAccJerkMeanY"           "timeBodyAccJerkMeanZ"           "timeBodyGyroMeanX"             
[13] "timeBodyGyroMeanY"              "timeBodyGyroMeanZ"              "timeBodyGyroJerkMeanX"         
[16] "timeBodyGyroJerkMeanY"          "timeBodyGyroJerkMeanZ"          "timeBodyAccMagMean"            
[19] "timeGravityAccMagMean"          "timeBodyAccJerkMagMean"         "timeBodyGyroMagMean"           
[22] "timeBodyGyroJerkMagMean"        "freqBodyAccMeanX"               "freqBodyAccMeanY"              
[25] "freqBodyAccMeanZ"               "freqBodyAccJerkMeanX"           "freqBodyAccJerkMeanY"          
[28] "freqBodyAccJerkMeanZ"           "freqBodyGyroMeanX"              "freqBodyGyroMeanY"             
[31] "freqBodyGyroMeanZ"              "freqBodyAccMagMean"             "freqBodyAccJerkMagMean"        
[34] "freqBodyGyroMagMean"            "freqBodyGyroJerkMagMean"        "timeBodyAccStandardDevX"       
[37] "timeBodyAccStandardDevY"        "timeBodyAccStandardDevZ"        "timeGravityAccStandardDevX"    
[40] "timeGravityAccStandardDevY"     "timeGravityAccStandardDevZ"     "timeBodyAccJerkStandardDevX"   
[43] "timeBodyAccJerkStandardDevY"    "timeBodyAccJerkStandardDevZ"    "timeBodyGyroStandardDevX"      
[46] "timeBodyGyroStandardDevY"       "timeBodyGyroStandardDevZ"       "timeBodyGyroJerkStandardDevX"  
[49] "timeBodyGyroJerkStandardDevY"   "timeBodyGyroJerkStandardDevZ"   "timeBodyAccMagStandardDev"     
[52] "timeGravityAccMagStandardDev"   "timeBodyAccJerkMagStandardDev"  "timeBodyGyroMagStandardDev"    
[55] "timeBodyGyroJerkMagStandardDev" "freqBodyAccStandardDevX"        "freqBodyAccStandardDevY"       
[58] "freqBodyAccStandardDevZ"        "freqBodyAccJerkStandardDevX"    "freqBodyAccJerkStandardDevY"   
[61] "freqBodyAccJerkStandardDevZ"    "freqBodyGyroStandardDevX"       "freqBodyGyroStandardDevY"      
[64] "freqBodyGyroStandardDevZ"       "freqBodyAccMagStandardDev"      "freqBodyAccJerkMagStandardDev" 
[67] "freqBodyGyroMagStandardDev"     "freqBodyGyroJerkMagStandardDev"

###Variables

Subjects/Activities

> $ Subject                       : int  1 1 1 1 1 1 2 2 2 2 ... (1 through 30. That it is an integer is not relevant to the data.)
> $ Activity                      : Factor w/ 6 levels "LAYING","SITTING",..: 4 6 5 2 3 1 4 6 5 2 ... (See details above)

Time Body Means of Means

> $ timeBodyAccMeanX              : num  0.277 0.255 0.289 0.261 0.279 ...
> $ timeBodyAccMeanY              : num  -0.01738 -0.02395 -0.00992 -0.00131 -0.01614 ...
> $ timeBodyAccMeanZ              : num  -0.1111 -0.0973 -0.1076 -0.1045 -0.1106 ...
> $ timeGravityAccMeanX           : num  0.935 0.893 0.932 0.832 0.943 ...
> $ timeGravityAccMeanY           : num  -0.282 -0.362 -0.267 0.204 -0.273 ...
> $ timeGravityAccMeanZ           : num  -0.0681 -0.0754 -0.0621 0.332 0.0135 ...
> $ timeBodyAccJerkMeanX          : num  0.074 0.1014 0.0542 0.0775 0.0754 ...
> $ timeBodyAccJerkMeanY          : num  0.028272 0.019486 0.02965 -0.000619 0.007976 ...
> $ timeBodyAccJerkMeanZ          : num  -0.00417 -0.04556 -0.01097 -0.00337 -0.00369 ...
> $ timeBodyGyroMeanX             : num  -0.0418 0.0505 -0.0351 -0.0454 -0.024 ...
> $ timeBodyGyroMeanY             : num  -0.0695 -0.1662 -0.0909 -0.0919 -0.0594 ...
> $ timeBodyGyroMeanZ             : num  0.0849 0.0584 0.0901 0.0629 0.0748 ...
> $ timeBodyGyroJerkMeanX         : num  -0.09 -0.1222 -0.074 -0.0937 -0.0996 ...
> $ timeBodyGyroJerkMeanY         : num  -0.0398 -0.0421 -0.044 -0.0402 -0.0441 ...
> $ timeBodyGyroJerkMeanZ         : num  -0.0461 -0.0407 -0.027 -0.0467 -0.049 ...
> $ timeBodyAccMagMean            : num  -0.137 -0.1299 0.0272 -0.9485 -0.9843 ...
> $ timeGravityAccMagMean         : num  -0.137 -0.1299 0.0272 -0.9485 -0.9843 ...
> $ timeBodyAccJerkMagMean        : num  -0.1414 -0.4665 -0.0894 -0.9874 -0.9924 ...
> $ timeBodyGyroMagMean           : num  -0.161 -0.1267 -0.0757 -0.9309 -0.9765 ...
> $ timeBodyGyroJerkMagMean       : num  -0.299 -0.595 -0.295 -0.992 -0.995 ...

Frequency Body Means of Means

> $ freqBodyAccMeanX              : num  -0.2028 -0.4043 0.0382 -0.9796 -0.9952 ...
> $ freqBodyAccMeanY              : num  0.08971 -0.19098 0.00155 -0.94408 -0.97707 ...
> $ freqBodyAccMeanZ              : num  -0.332 -0.433 -0.226 -0.959 -0.985 ...
> $ freqBodyAccJerkMeanX          : num  -0.1705 -0.4799 -0.0277 -0.9866 -0.9946 ...
> $ freqBodyAccJerkMeanY          : num  -0.0352 -0.4134 -0.1287 -0.9816 -0.9854 ...
> $ freqBodyAccJerkMeanZ          : num  -0.469 -0.685 -0.288 -0.986 -0.991 ...
> $ freqBodyGyroMeanX             : num  -0.339 -0.493 -0.352 -0.976 -0.986 ...
> $ freqBodyGyroMeanY             : num  -0.1031 -0.3195 -0.0557 -0.9758 -0.989 ...
> $ freqBodyGyroMeanZ             : num  -0.2559 -0.4536 -0.0319 -0.9513 -0.9808 ...
> $ freqBodyAccMagMean            : num  -0.1286 -0.3524 0.0966 -0.9478 -0.9854 ...
> $ freqBodyAccJerkMagMean        : num  -0.0571 -0.4427 0.0262 -0.9853 -0.9925 ...
> $ freqBodyGyroMagMean           : num  -0.199 -0.326 -0.186 -0.958 -0.985 ...
> $ freqBodyGyroJerkMagMean       : num  -0.319 -0.635 -0.282 -0.99 -0.995 ...

Time Body Means of Standard Deviations

> $ timeBodyAccStandardDevX       : num  -0.284 -0.355 0.03 -0.977 -0.996 ...
> $ timeBodyAccStandardDevY       : num  0.11446 -0.00232 -0.03194 -0.92262 -0.97319 ...
> $ timeBodyAccStandardDevZ       : num  -0.26 -0.0195 -0.2304 -0.9396 -0.9798 ...
> $ timeGravityAccStandardDevX    : num  -0.977 -0.956 -0.951 -0.968 -0.994 ...
> $ timeGravityAccStandardDevY    : num  -0.971 -0.953 -0.937 -0.936 -0.981 ...
> $ timeGravityAccStandardDevZ    : num  -0.948 -0.912 -0.896 -0.949 -0.976 ...
> $ timeBodyAccJerkStandardDevX   : num  -0.1136 -0.4468 -0.0123 -0.9864 -0.9946 ...
> $ timeBodyAccJerkStandardDevY   : num  0.067 -0.378 -0.102 -0.981 -0.986 ...
> $ timeBodyAccJerkStandardDevZ   : num  -0.503 -0.707 -0.346 -0.988 -0.992 ...
> $ timeBodyGyroStandardDevX      : num  -0.474 -0.545 -0.458 -0.977 -0.987 ...
> $ timeBodyGyroStandardDevY      : num  -0.05461 0.00411 -0.12635 -0.96647 -0.98773 ...
> $ timeBodyGyroStandardDevZ      : num  -0.344 -0.507 -0.125 -0.941 -0.981 ...
> $ timeBodyGyroJerkStandardDevX  : num  -0.207 -0.615 -0.487 -0.992 -0.993 ...
> $ timeBodyGyroJerkStandardDevY  : num  -0.304 -0.602 -0.239 -0.99 -0.995 ...
> $ timeBodyGyroJerkStandardDevZ  : num  -0.404 -0.606 -0.269 -0.988 -0.992 ...
> $ timeBodyAccMagStandardDev     : num  -0.2197 -0.325 0.0199 -0.9271 -0.9819 ...
> $ timeGravityAccMagStandardDev  : num  -0.2197 -0.325 0.0199 -0.9271 -0.9819 ...
> $ timeBodyAccJerkMagStandardDev : num  -0.0745 -0.479 -0.0258 -0.9841 -0.9931 ...
> $ timeBodyGyroMagStandardDev    : num  -0.187 -0.149 -0.226 -0.935 -0.979 ...
> $ timeBodyGyroJerkMagStandardDev: num  -0.325 -0.649 -0.307 -0.988 -0.995 ...

Frequency Body Means of Standard Deviations

> $ freqBodyAccStandardDevX       : num  -0.3191 -0.3374 0.0243 -0.9764 -0.996 ...
> $ freqBodyAccStandardDevY       : num  0.056 0.0218 -0.113 -0.9173 -0.9723 ...
> $ freqBodyAccStandardDevZ       : num  -0.28 0.086 -0.298 -0.934 -0.978 ...
> $ freqBodyAccJerkStandardDevX   : num  -0.1336 -0.4619 -0.0863 -0.9875 -0.9951 ...
> $ freqBodyAccJerkStandardDevY   : num  0.107 -0.382 -0.135 -0.983 -0.987 ...
> $ freqBodyAccJerkStandardDevZ   : num  -0.535 -0.726 -0.402 -0.988 -0.992 ...
> $ freqBodyGyroStandardDevX      : num  -0.517 -0.566 -0.495 -0.978 -0.987 ...
> $ freqBodyGyroStandardDevY      : num  -0.0335 0.1515 -0.1814 -0.9623 -0.9871 ...
> $ freqBodyGyroStandardDevZ      : num  -0.437 -0.572 -0.238 -0.944 -0.982 ...
> $ freqBodyAccMagStandardDev     : num  -0.398 -0.416 -0.187 -0.928 -0.982 ...
> $ freqBodyAccJerkMagStandardDev : num  -0.103 -0.533 -0.104 -0.982 -0.993 ...
> $ freqBodyGyroMagStandardDev    : num  -0.321 -0.183 -0.398 -0.932 -0.978 ...
> $ freqBodyGyroJerkMagStandardDev: num  -0.382 -0.694 -0.392 -0.987 -0.995 ...

##Sources
This codebook was modeled on that provided here: _https://gist.github.com/JorisSchut/dbc1fc0402f28cad9b41_
